require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AndroidTorch' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-torch', :path => '../node_modules/react-native-torch'

  pod 'react-native-screen-brightness', :path => '../node_modules/react-native-screen-brightness'


  pod 'SRSRadialGradient', :path => '../node_modules/react-native-radial-gradient'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'AndroidTorchTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'AndroidTorch-tvOS' do
  # Pods for AndroidTorch-tvOS

  target 'AndroidTorch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
